openidprovider:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: openidprovider_blazor
    ports:
      - "9330:9330"
    environment:
      - ASPNETCORE_ENVIRONMENT=Production
      - ASPNETCORE_URLS=http://+:${PORT:-9330}
      - ConnectionStrings__DefaultConnection=Host=${{PostgreSQL.PGHOST}};Port=${{PostgreSQL.PGPORT}};Database=${{PostgreSQL.PGDATABASE}};Username=${{PostgreSQL.PGUSER}};Password=${{PostgreSQL.PGPASSWORD}}
      - DATAPROTECTION_KEYS_PATH=/data-protection-keys
    depends_on:
      postgres_db:
        condition: service_started
      volume_setter:
        condition: service_completed_successfully
    volumes:
      - dataprotection_keys:/data-protection-keys
    networks:
      - openid_network